examples/mnist_conv_dnn.py, lasagne/conftest.py, lasagne/layers/__init__.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py, lasagne/tests/test_examples.py, requirements.txt, setup.cfg
test_conv.py tests three conv 2d layer implementations using mostly
default parameters.  
The tests run convolutions with small kernels on small inputs.  (Which
is why it doesn't work with cuda-convnet.)  The convolution math was
done by hand, to allow checking actual outputs against expected
outputs.
The tests so far did turn out a bit hairy, maybe hard to follow.
Also, there's no way a few generic tests like this one could cover all
the special cases between the different implementations.  But it does
maybe cover a lot of common ground between them.  Interested to hear
what people think.
A part of this pull request changes the way that modules with missing
dependencies are dealt with, particurly lasagne.layers.dnn and
lasagne.layers.cuda_convnet.
Previously, these two modules failed at …
=> Add a few conv2d layer tests

lasagne/layers/base.py, lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dense.py, lasagne/layers/dnn.py, lasagne/layers/merge.py, lasagne/layers/noise.py, lasagne/layers/pool.py, lasagne/layers/shape.py, lasagne/tests/layers/test_base.py, lasagne/tests/layers/test_dense.py
As discussed in #17, it seemed to be a good idea to allow Layer instances to be constructed from input shapes rather than other Layer instances. While `get_output()` would not work for such layers, they could still be used standalone with `get_output_for()` and `get_output_shape_for()` -- after all, a layer only needs to know about its input and input shape to function.
We thought that implementing this would only touch the `Layer` base class (and the `MultipleInputsLayer` base class). However, while implementing it, I found that several other layer implementations rely on `self.input_layer.get_output_shape()` to work. There are about four ways of solving it:
1. Distinguishing between `self.input_layer` being a shape tuple or a layer in each of these cases
2. Moving this distinction into …
=> Allow Layers to be constructed from input shapes

lasagne/layers/__init__.py, lasagne/tests/layers/test_conv.py
also updated convolution implementation tests to match. @dnouri does this look okay? You wrote the tests originally so I guess you should have a look.
=> removed automatic import of modules with GPU-related dependencies.

lasagne/layers/helper.py
This should fix the issue I mentioned here:
https://github.com/benanne/Lasagne/pull/52#issuecomment-72264767
I.e., now that a layer can have an input attribute which is `None`, `get_all_layers` can return a list which has entries which are `None`.  This causes problems, e.g. causes `get_all_params` to fail because 
```Python
layers = get_all_layers(layer)
params = sum([l.get_params() for l in layers], [])
```
I'm not 100% sure this is the best way/only place to fix this, but I think it is.
=> Preventing None from appearing in get_all_layers' returned list

lasagne/layers/shape.py, lasagne/tests/layers/test_shape.py
This adds `layers.ReshapeLayer`.
In addition to supporting fixed shapes and shapes with `-1` for one dimension to be inferred automatically, it also supports `None` for dimensions to be copied from the input shape. This should be handy especially for the batch size, so you can keep the batch size constant even if you don't know its value and still have the `-1` available for automatically inferring any of the other dimensions. (Only works if the batch size is the first dimension, though.)
If you're fine with the proposed interface and functionality, I'll add tests. If you have any ingenious idea on how to improve the "copy dimensions" feature, let me know.
=> Add ReshapeLayer

lasagne/layers/shape.py
This removes the usage of `reduce` from the `ReshapeLayer` implementation (noted here: https://github.com/benanne/Lasagne/pull/94#issuecomment-73416833) so it's compatible with Python 3.
=> ReshapeLayer: ensure Python 3 compatibility

docs/user/installation.rst
Tiny PR that addresses today's "pip install does'nt work?" mail on the mailing list.
=> Add note to install instructions about lack of PyPI release

lasagne/tests/test_updates.py, lasagne/tests/test_utils.py, lasagne/updates.py, lasagne/utils.py
Here's an attempt at weight norm constraints as we discussed in #84.  I also did a little PEP8 cleanup in update.py (mostly line lengths stuff).
Unless I totally overlooked an easy assumption, it seems like we have to handle all the different types of parameter dimensionalities differently (not quite as clean as in the default Uniform initializer).  So, it makes assumptions about the mean of the dimensions in a 2D and 4D parameter array.  
Let me know what you guys think.  I'll add better docs later.
=> Weight Norm Constraints

docs/modules/utils.rst, lasagne/layers/merge.py, lasagne/utils.py
Addresses #151 (but does not close it; we still need to remove the function for the first release).
=> Deprecate lasagne.utils.concatenate and do not use it within library

examples/mnist.py, examples/mnist_conv.py, examples/mnist_conv_cc.py, examples/mnist_conv_dnn.py
I was running the examples recently to compare the speed of Theano's convolutions (FFT and non-FFT), cudnn, and cuda_convnet, and in the process I made a few changes to the example files.  This PR reflects those changes, which are:
- Switched string syntax from `%` to `format`, because `%` are ["obsolete and may go away in future versions of Python"](https://docs.python.org/release/3.1.5/library/stdtypes.html#old-string-formatting-operations)
- Making it so that issuing ctrl-C while training just exits the script cleanly without a traceback (just an aesthetic thing when you don't want it to train for 500 epochs)
- Added print statements for loading data and building the models
- Added the amount of time each epoch took to the print statement
I can split these up if you want, or remove one …
=> Misc diagnostics/cleanup to examples

lasagne/layers/input.py
It wasn't documented that the `shape` of `InputLayer` may include `None`s, nor what that would be useful for.
=> Document variable `InputLayer` shape dimensions

examples/mnist.py, lasagne/objectives.py, lasagne/tests/test_objectives.py
Masked objectives allow specified rows to be ignored when computing the loss value. For classification problems, this can be useful if training or test set is not an exact multiple of the mini-batch size; on the last mini-batch you provide a mask with zeros for the entries in the mini-batch for which you do not have data. For image segmentation problems the mask can be used to define a region of interest.
=> Objectives now have an optional mask.

lasagne/__init__.py, lasagne/layers/__init__.py, lasagne/layers/normalization.py, lasagne/tests/layers/test_normalization.py
This is a first stab at a 2D cross-channel LRN layer. Lines 52 through 61 are pretty much verbatim from `pylearn2`, except for some variable renaming. I added some comments and the `lasagne` wrapping. It gets the job done but perhaps it could be generalized to handle `cb01` as well as `bc01`, though in the former case `cuda-convnet` could be preferable. Maybe a 1D version would also be desirable, though I don't know if anyone does this for 1D data.
=> Cross-channel Local response normalization

lasagne/nonlinearities.py, lasagne/tests/test_nonlinearities.py
This adds the leaky rectifier nonlinearity with custom leakiness. Example use:
```python
input_var = theano.matrix('x')
layer = InputLayer((10, 20), input_var)
layer = DenseLayer(30, nonlinearity=lasagne.nonlinearities.leaky_rectify(0.05))
```
It's obviously a callable class, not a function. We can discuss whether to name it `leaky_rectify` to blend in with the others or `LeakyRectify` to set it apart. Thinking about it, I'm actually leaning towards the latter.
=> Leaky rectifier nonlinearity

lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py
Adds test coverage of `None` in the b01 dimensions of Conv layers, and updates those that needed fixes to support it.
This partially resolves https://github.com/benanne/Lasagne/issues/166, although it needs to be documented somewhere that this is the proper way to handle variable input size, since until https://github.com/Theano/Theano/issues/2620 is fixed, it will still be possible to get results of the wrong shape without an error.
=> Make Conv layers support None in input shape

lasagne/layers/base.py, lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dense.py, lasagne/layers/dnn.py, lasagne/layers/input.py, lasagne/layers/merge.py, lasagne/layers/noise.py, lasagne/layers/normalization.py, lasagne/layers/pool.py, lasagne/layers/shape.py, lasagne/objectives.py, lasagne/tests/layers/test_base.py, lasagne/tests/test_objectives.py
This removes `*args` from `get_output()` and `get_output_for()`, leaving only `**kwargs` for customizations.
@benanne stated that the `*args` [were there intentionally](https://github.com/benanne/Lasagne/issues/115#issuecomment-71394148), but without an existing use case. Later in the same thread we established that we should not include `*args` [for the layer constructor](https://github.com/benanne/Lasagne/issues/115#issuecomment-71466435) to avoid people writing code that can break in future (or, put differently, to allow us to add additional arguments without breaking people's existing code).
In any case, please see this as a proposal to be discussed rather than a request to be merged, it just took 5 minutes.
=> Remove *args from get_output() and get_output_for()

lasagne/layers/pool.py
I haven't tested thoroughly (not sure how to?) but it appears to push out data of the correct shape, following Colin's example in #166 with a few modifications.
There are a few bits of code that look like they code be simplified:
* forced integer division inside `pool_output_length` (copied from `get_output_shape_for` previously)
* the `ignore_border` check
I'm happy to fix those too prior to merging.
=> added None propagation to pooling operators

lasagne/layers/helper.py, lasagne/tests/layers/test_helper.py
This renames the current implementation of `lasagne.layers.get_all_layers()` to `lasagne.layers.get_all_layers_old()` and installs a new implementation `lasagne.layers.get_all_layers()` which is guaranteed (and tested) to return layers in topological order. This is a requirement for #104, among others.
It currently gives a warning whenever it is called, along with a note on how to disable that. The warning serves to notify all users of the transition and `get_all_layers_old()` eases it, but both should be removed for the first release of Lasagne.
=> Topological order for get_all_layers()

lasagne/layers/helper.py
I just got tricked by Lasagne staying silent when `set_all_param_values()` was called with an empty `values` list. This PR throws an exception if there are not enough or too many values.
=> Make set_all_param_values() check the number of provided values

lasagne/utils.py
`lasagne.utils.concatenate` has been deprecated for a month, we should remove it before we forget.
=> Remove lasagne.utils.concatenate

examples/mnist_conv.py, examples/mnist_conv_cc.py, examples/mnist_conv_dnn.py, lasagne/init.py, lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dense.py, lasagne/layers/dnn.py, lasagne/tests/test_init.py
This PR cleans up the `lasagne.init` module. It introduces separate classes for "Glorot-style" initialization, `GlorotUniform` and `GlorotNormal`.
This means `Uniform` no longer does Glorot-style init by default. Instead, it will use a default range of (-0.01, 0.01). I've added a warning to alert people of this, in case they're using `Uniform` in this way. Their training runs might suddenly take a lot longer to converge!
Accordingly, I've also changed the default initialization to `GlorotUniform` everywhere in the library.
I've added separate `GlorotUniform_c01b` and `GlorotNormal_c01b` initializers for the c01b case (useful for cuda-convnet-based layers). We discussed a fancier approach using `fan_in` and `fan_out` parameters in #49, but for now I don't think this will be worth it. …
=> Revamp lasagne.init

lasagne/layers/pool.py, lasagne/tests/layers/test_pool.py
This adds a `MaxPool1DLayer` that just uses `max_pool_2d` with an extra dimension of size 1. It also adds rudimentary tests for `MaxPool1DLayer` and `MaxPool2DLayer`.
=> add MaxPool1DLayer + tests

lasagne/init.py, lasagne/layers/cuda_convnet.py, lasagne/tests/test_init.py
I figured I might as well go ahead and add them.
This should supersede #165: `lasagne.init.HeNormal('relu')` should be equivalent to `lasagne.init.ReluNormal()` introduced in that PR.
For some reason I botched my pep8/flake8/pytest install on this PC, so I'm counting on Travis here :)
=> He-style initializers

lasagne/updates.py
This pulls out `apply_momentum` and `apply_nesterov_momentum` as I suggested in https://github.com/benanne/Lasagne/issues/190#issuecomment-88960154. Also it changes the update functions to accept either a cost expression or a list of gradients, and to return OrderedDicts instead of `(param, update)` tuple lists. Finally, it adds numpy-style docstrings to `sgd` and the four `momentum` functions, and converts the `norm_constraint` docstring to numpy format.
=> Modular momentum updates plus docstrings

examples/mnist_conv.py, examples/mnist_conv_cc.py, examples/mnist_conv_dnn.py, lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dnn.py, lasagne/layers/pool.py, lasagne/tests/layers/test_conv.py, lasagne/tests/layers/test_pool.py, lasagne/utils.py
This is to close #207 
I've made changes to use `filter_size`, `pool_size` and `stride` throughout all conv and pooling layers. 
Added a helper function `as_tuple` in `utils.py` which takes an input and a length and returns a tuple of that length, and use it in the 2D layers to accept either a number or tuple for `pool_size` and `stride`. 
I also added some tests for the cuda_convnet and dnn pooling layers, and updated the examples to use `pool_size`.
=> Unify keyword argument names for convolution and pooling

lasagne/layers/pool.py, lasagne/tests/layers/test_pool.py
This is to close https://github.com/Lasagne/Lasagne/issues/208
I decided to simply remove the call to pool_output_length instead of changing its defaults because
- I'd prefer that function to require explicit parameters (and I removed the defaults that were there), since that avoids duplicating code for default handling and may help expose any bugs in layers calling it.
- Since `FeaturePoolLayer` doesn't use any of the more complicated parameters (and it doesn't seem like it will in the future) there's no real need for the helper function.
- The simple division is a bit easier to understand if you're just reading the code and aren't familiar with the helper function.
I also added a test for this layer, and rewrote some of the docstring and `get_output_for` to be a bit cleaner (in my …
=> Featurepool

docs/conf.py, docs/requirements.txt
I have no way to test this, I think... unless readthedocs.org can build docs off a branch as a test, I'll look into that (but I doubt it). Suggestions to maximize the chance of this working are very welcome :)
=> Mock theano.config so GPU-dependent modules show up on readhtedocs.org

docs/conf.py
This is a second attempt to make the docs for the alternative convolutional layer implementations show up on readthedocs.org.
~~I 'fixed' the issue by moving the imports of `GpuCorrMM` (corrmm) and `FilterActs` (cuda_convnet) into the methods were they are used. This allows readthedocs.org to import the modules and grab the docstrings.~~
~~The downside of this fix is that `lasagne.layers.cuda_convnet` will now no longer fail at import time if pylearn2 is not available. That's not good. I don't know how else to fix it though, and having the docs show up seems a bit more important. If someone can come up with a good work-around, let me know.~~
(See #223 for the previous attempt - it didn't work but I think it was a necessary step.)
EDIT: I changed the approach to avoid having to import …
=> Make lasagne.layers.corrmm / dnn / cuda_convnet docs show up on readthedocs.org, attempt 2

lasagne/layers/dense.py
This adds a layer class that just performs a nonlinearity.
This is for use in conjunction with MultipleInputsLayer subclasses, which just add or concatenate outputs from layers.  For example, one might want to take inputs of length n and m, perform linear transformations on them using DenseLayer objects, then add the transformed outputs with an ElemwiseSumLayer, and then use this class to apply a nonlinearity (note that this would be different from applying the nonlinearity and then adding).  Alternatively, one could use a ConcatLayer followed by a DenseLayer, but concatenation is less efficient than adding.
=> added NonlinearityOnlyLayer for use with MultipleInputLayer

lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/dnn.py
This one was easy, it turns out `Conv2DMMLayer` and `Conv2DDNNLayer` have the exact same interface so I could copy the docstring with almost no modifications.
I will merge this tomorrow unless there are any remarks.
=> lasagne.layers.corrmm.Conv2DMMLayer docs

examples/mnist.py, lasagne/layers/base.py, lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dense.py, lasagne/layers/dnn.py, lasagne/layers/helper.py, lasagne/layers/input.py, lasagne/layers/shape.py, lasagne/objectives.py, lasagne/tests/layers/conftest.py, lasagne/tests/layers/test_base.py, lasagne/tests/layers/test_conv.py, lasagne/tests/layers/test_helper.py, lasagne/tests/layers/test_input.py, lasagne/tests/layers/test_noise.py, lasagne/tests/layers/test_normalization.py, lasagne/tests/layers/test_pool.py, lasagne/tests/layers/test_shape.py, lasagne/tests/test_objectives.py, lasagne/updates.py
To address #104, this moves `get_output()` out of the layer class hierarchy and turns it into a helper function `lasagne.layers.get_output()`. This is work in progress.
TODO:
The current tests don't run through because they rely on everything-goes `Mock()` instances. That is, they always have a `input_layers` attribute, which tricks `get_all_layers()`. Changing `get_all_layers()` to first check for the `input_layer` attribute isn't better either, because every `Mock()` instance also has a `input_layer` attribute which is a `Mock()` instance with an `input_layer` attribute. Changing the `Mock()` instances to only have the attributes they should makes the tests fail in other ways because they assume `get_output()` to be called where the new code calls `get_output_for()` or returns …
=> turn get_output() into a global function

lasagne/utils.py
This changes `lasagne.utils.floatX` to support scalars (see https://github.com/Lasagne/Lasagne/issues/133#issuecomment-102005873), and to not copy the input if it's already in the correct dtype.
=> Make lasagne.utils.floatX support scalars and avoid copies when possible

lasagne/layers/shape.py
As discussed in https://github.com/skaae/nntools/commit/0c8386d27cfc33f95ef22e39e11e6b5efff62b0d#commitcomment-11193981, this changes the `ReshapeLayer` docstring to be closer to my original version, but with reordered explanations and a bullet point list to make it easier to follow. Additionally, the second and third usage example are merged into a single one that shows all features without leading people into thinking it could be used for transposing data.
(What's the way to check if the bullet point markup is correct?)
=> Clearer ReshapeLayer docstring (shape specification and usage example)

docs/modules/layers.rst, lasagne/layers/base.py, lasagne/layers/helper.py, lasagne/layers/merge.py, lasagne/tests/layers/test_base.py, lasagne/tests/layers/test_helper.py
With #182 we can now rename the confusing `MultipleInputsLayer` to `MergeLayer` (see #200) without ending up in rebase hell!
=> rename MultipleInputsLayer to MergeLayer

docs/modules/init.rst, docs/modules/objectives.rst, docs/modules/updates.rst, lasagne/init.py, lasagne/layers/dense.py, lasagne/layers/noise.py, lasagne/updates.py
Fixing several errors in the docstring markup. @skaae, please have a quick look at the diff to see what's important for future contributions!
Useful references:
* https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt
* https://github.com/numpy/numpy/blob/master/numpy/fft/info.py
* http://docs.scipy.org/doc/numpy/reference/routines.fft.html
Something's still wrong with how the references render in Sphinx, as well as the parameter descriptions (I think they are rendered as block quotes, with a grey bar on the left and a larger font size).
/edit: The most important gotchas: Section names need to follow the first document, reference definitions need to follow the first document, math needs to have backslashes escaped in docstrings.
=> Docstring markup fixes: Section names, math and reference syntax

lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dense.py, lasagne/layers/dnn.py
I've only done the convolution layer so far. It was mostly copy paste from the other implementations, but the `dimshuffle` and `partial_sum` arguments required some extra work. The notes section is also quite beefy because all the limitations of the cuda-convnet convolution implementation need to be explained.
I'll do the pooling layer and the bc01/c01b shuffle layers next.
=> lasagne.layers.cuda_convnet documentation

lasagne/layers/embedding.py, lasagne/tests/layers/test_embedding.py
The previous version of the embedding layer did only handle 1d output. Minor change that generalize it 
to any dimension input.
=> generalize embedding

docs/conf.py, docs/requirements.txt
This changes the Sphinx theme to `sphinx_rtd_theme`. Content looks a lot nicer than for the bootstrap theme, it's also mobile-friendly (the sidebar collapses for narrow screens), and it's included with recent versions of sphinx (so you can also build it locally as before).
The next best bet would be the theme used by the Python documentation, with a sticky sidebar. I've added that one as well (called `"classic"` in Sphinx 1.3), but left it commented out. In my opinion, the readthedocs theme styles the "class lasagne.Xyz" lines much better, which is useful for pages that have a lot of classes (such as the `lasagne.layers` API reference).
=> Change Sphinx theme to the one provided by readthedocs

docs/modules/nonlinearities.rst, lasagne/nonlinearities.py
Fixes the `Methods` section of the `LeakyRectify` docstring, documents it a bit more extensively, and properly documents the `leaky_rectify` shortcut (using the technique suggested in the numpydoc howto). While we're at it, also adds a `very_leaky_rectify` shortcut, as this seems to become more popular.
=> Extend and fix markup of LeakyRectify docstring

lasagne/layers/dense.py, lasagne/layers/shape.py, lasagne/tests/layers/test_dense.py, lasagne/tests/layers/test_input.py, lasagne/tests/layers/test_merge.py, lasagne/tests/layers/test_normalization.py, lasagne/tests/layers/test_shape.py, lasagne/tests/test_nonlinearities.py, lasagne/tests/test_theano_extensions.py, lasagne/tests/test_utils.py
This PR (previously https://github.com/Lasagne/Lasagne/pull/264) extends test coverage on dense.py, theano_extensions, nonlinearities.py, input.py, merge.py, normalization.py, shape.py and utils.py.
It also fixes a minor bug in NINLayer and remove an extra check from DimshuffleLayer
=> Extend test coverage

lasagne/layers/base.py, lasagne/tests/layers/test_base.py
This is going to be a collection of tests to improve test coverage across the library. So far I've only done `base.py`, which should now be 100% covered when we get rid of the deprecated stuff. Other than that I'll be focusing mostly on the convolution implementations for now. If anyone wants to help we can try to divide the work a little. It would be nice to get the coverage up in the 90%+ range before we release the library :)
For clarity's sake, I'm of course aware that good coverage does not necessarily mean the tests are good - but it's an important first step!
=> improve test coverage

lasagne/tests/test_updates.py, lasagne/updates.py
To add some coverage of the update rules, I wrote a test comparing their results to values calculated using the Torch optim package. 
In the process, I found a discrepancy with the ADAM updates, after looking at the paper I think the Torch version is correct but I'd appreciate a second opinion.
=> Updates test coverage

lasagne/layers/helper.py, lasagne/layers/pool.py, lasagne/tests/layers/test_pool.py
Adds a few tests to complete coverage for pool.py, and adds `pragma no cover` for the deprecated helper functions.
=> Coverage for pool.py, helper.py

lasagne/layers/base.py, lasagne/layers/helper.py
This sets `stacklevel=2` for the `get_output`, `get_output_shape` and `get_bias_params` deprecation warnings so they point at the offending deprecated function call (i.e., the point in code where you call a deprecated function) rather than the `warnings.warn` call (i.e., the point in Lasagne where we raise the warning). This makes it much easier to track down any remnants of the good old days, err, the old API in user code.
=> Change stacklevel for deprecation warnings to point at function call

lasagne/tests/test_utils.py, lasagne/utils.py
This changes `lasagne.utils.create_param()` to accept arbitrary iterables as shapes, not only tuples. Before, when giving a `list` as a shape, the function would fail with an unhelpful "the provided callable did not return a value with the correct shape", because the list was later compared against a tuple. (I'd also be fine with a meaningful error message, but adding `shape = tuple(shape)` is easy enough and more convenient.)
Besides, I've changed the "Notes" section, which still assumed that `create_param()` was a `Layer` method.
=> Make lasagne.utils.create_param() accept iterables as shapes

lasagne/__init__.py, setup.py
As per the discussion in #263, this updates the version in setup.py to be pep440 compatible, and adds `lasagne.__version__`, which mirrors the package's version in setup.py.
I vaguely remember having some problems with `pkg_resources.get_version()` and readthedocs, but can't remember what it was.  I assume the Lasagne package is set up normally with readthedocs.  `get_version` would fail if it weren't.
=> Add lasagne.__version__ which mirrors the package's version.

lasagne/updates.py
You couldn't apply momentum to ADAM updates because it still used a list for the updates. This converts the list to an OrderedDict.
=> Use OrderedDict for ADAM updates to be compatible with other updates.

lasagne/layers/noise.py
This partially addresses https://github.com/Lasagne/Lasagne/issues/6, which came up on the mailing list again a few days ago (https://groups.google.com/forum/#!topic/lasagne-users/85-6gxygtIo).
By making `_srng` a member of each layer which is initialized from numpy, the user only needs to call `np.random.seed` at the start of their code to get reproducible behavior.
=> move srng into noise layers, seed from numpy

lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py, lasagne/tests/layers/test_dense.py, lasagne/tests/layers/test_pool.py
This PR does a few things:
* fixes a bug in all convolution implementations which made bias-less layers unusable (the same one that @ebenolson fixed in `NINLayer`, see https://github.com/ebenolson/Lasagne/commit/ffce108e87d4f14a7e2c2499bb4ccb1c9c86f02e)
* moves the `border_mode` validity check into the constructor for all layers, so constructing a layer with an invalid border mode string fails as early as possible (previously this check was in `get_output_for()` and `get_output_shape_for()` for a few implementations)
* adds tests for bias-less layers (`b=None`), linear layers (`nonlinearity=None`) and invalid border mode checks
It brings coverage for `lasagne/layers/conv.py` up to almost 100%. It falls just two lines short of that: the `b=None` case in `get_output_for()` is not covered …
=> increase coverage for convolution layers

lasagne/tests/layers/test_conv.py
This replaces the Theano-based conv2d test set with one using numpy.
The multiple calls to `conv2d(...).eval()` were a taking a lot of time, on my machine this change brings the test collection time from 33.59 to 0.51 seconds.
=> use numpy for conv2d test sets

docs/_static/fix_rtd.css, docs/conf.py
This provides a workaround for https://github.com/snide/sphinx_rtd_theme/issues/149, the first point on the list of documentation layout issues that bothered me: https://github.com/Lasagne/Lasagne/issues/203#issuecomment-103983492. See "Parameters: leakiness" on the following page if you're unsure what I'm talking about: http://lasagne.readthedocs.org/en/latest/modules/nonlinearities.html#lasagne.nonlinearities.LeakyRectify
=> Fix vertical alignment mismatch in sphinx documentation

.coveragerc-nogpu, .travis.yml, README.rst
Apart from registering Lasagne on coveralls.io, this should be all that's needed for python-coveralls to do its work.
Related to #112: Improving test coverage.
=> Add coveralls.io

README.rst
This adds a license badge to the README file, making it easier to see the license we're using.
=> Add license badge to README

docs/conf.py
Fixes the issue noted in https://github.com/Lasagne/Lasagne/pull/262#issuecomment-109764518: The source code file was not inferred correctly for `lasagne.layers.*` members. In addition, changes the github links to highlight the full range of the entity rather than just the first line. (This is something I should add to numpy as well... after my vacation.)
=> Fix github source code links generated by Sphinx

lasagne/layers/shape.py, lasagne/tests/layers/test_shape.py
Allow symbolic variables in the shape specifcation when using the reshape layer.
Its discussed here: https://groups.google.com/forum/#!topic/lasagne-users/eA995V73K8I
One use case is to allow for both variable batchsize and sequence length when using recurrent nets.
It passes the tests but i'm not sure if it has some undesired consequences?
=> allow symbolic in reshape

docs/index.rst, docs/modules/regularization.rst
The PR with the reworked regularization code (#285) did not include the necessary files to make the module show up in the docs. This PR adds rudimentary versions of those. It's probably useful to flesh this out a bit, but let's do that at a later date.
=> Make regularization docs show up

lasagne/layers/base.py, lasagne/tests/layers/test_base.py, lasagne/tests/layers/test_helper.py, lasagne/tests/layers/test_noise.py, lasagne/tests/layers/test_pool.py, lasagne/tests/layers/test_shape.py, lasagne/tests/test_objectives.py, lasagne/tests/test_utils.py, lasagne/utils.py
This is a small change, I'm not sure if there are guidelines for contributions and how involved they should be. If small changes like this are ok, then I'll continue to make pull requests as I modify the library. If larger changes are preferred I'll hold off until I feel I've made a more substantial progress.  
I added an error message to catch the scenario where the conv+max pooling layers reduce an image size to 0 for smaller images. 
Previous error messages looked like this, and had a delay due to the SVD call during orthogonal initialization. 
```
...
File "/home/joncrall/code/ibeis_cnn/ibeis_cnn/models.py", line 1012, in build_model
W=init.Orthogonal(),
File "/home/joncrall/code/Lasagne/lasagne/layers/dense.py", line 72, in __init__
self.W = self.add_param(W, (num_inputs, num_units), …
```
=> Shape error message

.travis.yml, docs/requirements.txt, docs/user/development.rst, requirements-dev.txt, setup.cfg, setup.py
Necessary because different versions of pep8 will give different results.  See #271.
=> Add requirements-dev.txt for testing requirements.

lasagne/layers/helper.py, lasagne/tests/layers/test_helper.py
Recently I accidentally tried to load saved network parameters from a model with different numbers of units in the dense layers.  This passed by silently and I could not figure out why my network was not improving with more hidden units.  I think an error should be raised when loading saved weights changes the network structure.  This is closely related to https://github.com/Lasagne/Lasagne/pull/177.
=> Check that parameter shapes match value shapes when loading weights

lasagne/layers/shape.py, lasagne/tests/layers/test_shape.py
adds a `dim` argument to flatten that lets the user decide from which dimension the input should be flattend, e.g. `dim=1`(default) has the same behavior as the current flatten layer.
This is usefull if you have recurrent layer that has convolutional output.
=> add dim arg to flatten

lasagne/layers/conv.py, lasagne/tests/layers/test_conv.py
replaces the test of `conv_output_length` with a more complete version. Also changed the function to raise `ValueError` instead of `RuntimeError`.
=> more tests for conv_output_length

lasagne/layers/cuda_convnet.py, lasagne/tests/layers/test_pool.py
MaxPoolConv2DCCLayer should allow inputs whose dimensions are not known at compile-time to be specified with None.  I updated MaxPoolConv2DCCLayer to use pool_output_length in a similar manner to how Conv2DCCLayer uses conv_output_length.
I set ignore_border=False and pad=0 because MaxPool2DCCLayer does not support ignore_border or padding.
This was inspired by the discussion on [lasagne-users](https://groups.google.com/forum/#!topic/lasagne-users/72e1-EEAZGM).
=> Update MaxPool2DCCLayer to use pool_output_length

lasagne/utils.py
add note to one_hot function doc that refers potential users to the ability of categorical_crossentropy to handle integer vectors directly
=> one_hot docstring

docs/user/installation.rst, lasagne/__init__.py, requirements.txt, setup.py
For discussion, see #323.
`requirements.txt` has been changed to point to a recent Git version of Theano as per our discussion.  Install docs were updated, though necessary changes were minimal.  (Installation has become slightly more complicated though.)
I also did what @ebenolson suggested and removed `Theano` from dependencies in `setup.py`.  I've added a friendly error message for people who ignore the updated installation docs, run `pip install Lasagne` alone, and now get `ImportError theano`.  The point here is to avoid accidentally installing a too old version of Theano, which would then be hard to detect for us at runtime, and would lead to obscure errors as pointed out by @ebenolson.
=> Require Git version of Theano.  For #320.  See #323.

docs/user/installation.rst
This adds a lot of information to the installation instructions about how to install requirements (and where to find more information), what the `requirements.txt` and Theano version is about, how to install Lasagne from PyPI, github, source or without pip, and how to get GPU support working (with pointers to where to find more information), including cuDNN. That's a lot, but I think it's good to have everything in a central place. It's probably tough to find all this when you're a Theano newbie, and the Theano installation instructions are not terribly clean / up-to-date.
Resolves #339, resolves #316. (This should make [github close these issues automatically](https://github.com/blog/1506-closing-issues-via-pull-requests) on merging.)
=> Fleshed out installation instructions

lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py, lasagne/tests/test_utils.py, lasagne/utils.py
Continuation of #311. Closes #311. (So github knows.)
I'm starting from the relevant changes done by Martin, dropping all unrelated docstring style changes (sorry, they don't really belong here and they caused a merge conflict).
I'll try fixing all Python3- and cuDNN-related bugs now.
=> Merge border_mode with pad argument for convolutional layers

docs/user/installation.rst
Fixes the markup for a link added in #351 that I merged too quickly (it was in markdown instead of reST, and markdown seems so familiar on github...).
=> installation.rst: convert markdown to reST

lasagne/tests/layers/test_noise.py, lasagne/tests/test_init.py
Fixes `test_noise.py` and `test_init.py` to restore the original RNG in `lasagne.random` after calling `lasagne.random.set_rng()` for some tests. This ensures that tests called afterwards can still use `np.random.seed(...)` as expected, and don't start with a fixed seed.
(Note: We could also do `get_rng().seed(...)` instead of `set_rng(RandomState(...))`, but I think a side intention was to test whether `set_rng()` works.)
=> Ensure that tests calling set_rng() switch back to the default RNG

README.rst, docs/user/development.rst
This fleshes out the README file to show an example upfront so you know what to expect, and to point to installation instructions, documentation and contribution guidelines (although the latter should probably be fleshed out in the documentation).
See https://github.com/f0k/Lasagne/tree/readme for how it would look.
Closes #86 in passing.
=> Fleshed out README and design goals

docs/conf.py, docs/index.rst, docs/modules/layers.rst, docs/modules/layers/base.rst, docs/modules/layers/conv.rst, docs/modules/layers/corrmm.rst, docs/modules/layers/cuda_convnet.rst, docs/modules/layers/dense.rst, docs/modules/layers/dnn.rst, docs/modules/layers/embedding.rst, docs/modules/layers/helper.rst, docs/modules/layers/input.rst, docs/modules/layers/merge.rst, docs/modules/layers/noise.rst, docs/modules/layers/pool.rst, docs/modules/layers/recurrent.rst, docs/modules/layers/shape.rst, docs/modules/random.rst, lasagne/layers/dense.py, lasagne/layers/dnn.py, lasagne/layers/helper.py, lasagne/layers/noise.py, lasagne/layers/pool.py, lasagne/layers/recurrent.py, requirements-dev.txt
This splits up the `lasagne.layers` Sphinx documentation across multiple pages; one per submodule (but taking care to present all classes as belonging to the `lasagne.layers` namespace if appropriate). It requires Sphinx 1.2.3 to build because of a regression in more recent versions (see https://github.com/Lasagne/Lasagne/issues/203#issuecomment-121310595), but we use that one on readthedocs anyway (just note that a more recent version will omit the autosummary tables, so make sure to use Sphinx version 1.2.3 or the latest git version if building locally).
I've tried a few different options for the TOC and layout, and this is the best I found. It has a bunch of autosummary tables for `lasagne.layers`, and the TOC is set up such that clicking `Convolutional layers` in the left-hand navbar …
=> Split layer docs

lasagne/init.py, lasagne/layers/base.py, lasagne/layers/helper.py, lasagne/objectives.py, lasagne/tests/layers/test_pool.py
Resolves #345.
There's no instance of `warning`, `deprec` or `no cover` left (except for GPU-related `pragma: no cover` markers), and all the tests pass (actually had to fix one of them, though).
=> Remove deprecates

lasagne/updates.py
Fix dtype mismatching in function Adam( ) using f0k's suggestion: initiating `m_prev` and `v_prev` with `np.zeros`.
=> Fix issue #363

LICENSE, docs/conf.py, setup.py
Changes attributions in code, documentation and license to include all Lasagne contributors, not only (or not primarily) Sander. He's still explicitly named as the one who started the project, though!
Copied some sections about copyright and contribution agreement from Caffe's license file. Not sure if we need to include Caffe's license file now because Caffe's license text is covered by Caffe's license text? %-)
I've chosen our google group as the email address to contact the authors under. Seemed like the most reasonable option. (Theano has its *theano-dev* group there, but we don't have nor need one. Blocks and Fuel don't give an email address at all, which would also be an option.)
=> Attribute code to "Lasagne contributors"

docs/user/development.rst, docs/user/installation.rst
Resolves #367.
Mentions core team by name, moves the design goals further to the front, gives suggestions on what to contribute and technical instructions on how to contribute.
=> Rewrite of "Development" page in documentation

README.rst
With the additions in #366, github doesn't recognize the license file as being MIT any more. This PR just hard-codes the license type (as done by Blocks).
=> Fix license badge

lasagne/layers/cuda_convnet.py, lasagne/layers/dnn.py, lasagne/layers/pool.py, lasagne/tests/layers/test_pool.py
Resolves #371 (users would get slow pooling layers by default because `ignore_border=False` prevents cuDNN from being used). Adds a note about `ignore_border=True` slowing down computations. Unifies `*PoolLayer` interfaces to follow the same order of `pool_size, stride, pad, ignore_border, (mode)`, they were inconsistent before and sometimes not even matching the order in their own docstrings. Adapts the tests.
=> Unify *PoolLayer interfaces, new default ignore_border=True

CHANGES.rst, MANIFEST.in, docs/user/installation.rst, requirements.txt, setup.py
This adds a changelog as suggested in https://github.com/Lasagne/Lasagne/issues/74#issuecomment-130331059, updates `requirements.txt` to a Theano version supporting cuDNN v3 as suggested in https://github.com/Lasagne/Lasagne/issues/74#issuecomment-130390810, and changes the version number from `0.1.dev` to `0.1`.
It assumes we're going to tag the release as `v0.1` (that's how numpy and blocks do it, for example), not as `0.1` (that's how, hmm... some projects do it like this). I'm fine with either way. @dnouri might have a preference?
It would be nice to have a DOI badge in the README of the first release, but I'm not sure if it's possible to add the DOI badge before we tag the release, which we need to do in order to get a DOI. I'll investigate.
=> Prepare for first release

docs/conf.py, setup.py
This should be merged before merging any code changes (at the very least because the documentation on readthedocs uses the `dev` suffix to check whether to link to the `v0.1` tag or the `master` branch on github for source code).
I'm not sure if `0.2.dev` is the right choice, though. We could also go for `0.1.1.dev`. And it seems that's not a valid version string anyway, I've previously seen some tool (pip?) complain and change it to `0.1.dev0`. So we could also go for `0.2.dev0` and slightly adapt `docs/conf.py` to cope with that.
=> Bump to next development version

docs/modules/layers.rst, docs/modules/layers/special.rst, lasagne/layers/special.py, lasagne/tests/layers/test_special.py
Spatial transformer Layer
TODO/questions
* Tests. Added simple tests with https://github.com/skaae/nntools/commit/27faf05049c1889676ac2394d00b1b1677a72724
* I get an error when generating the docs. It seems to be related to objectives.rst??
* I put the TransformerLayer in a new file: transform.py. Do someone have a better suggestion?
=> Transformer

lasagne/layers/base.py
For the two base layers, the constructors were described in the constructor docstring, while the convention throughout Lasagne is to describe them in the class docstring. This PR fixes this just for consistency (and to not mislead contributors which have a look at `Layer` to check how a layer docstring is to be set up).
=> Move base layer constructor descriptions to class docstrings

lasagne/layers/merge.py, lasagne/tests/layers/test_merge.py
This PR adds automatic cropping to layers in lasagne/layers/merge.py.
This allows `ConcatLayer`, `ElemwiseMergeLayer` etc to automatically crop their inputs before use if the shapes don't match as required.
My use for this is in implementing segmentation algorithms such as [1]. While the same effect can be achieved using `SliceLayer`, manually computing the slice size can be a pain, so adding automatic cropping to the merge layers simplifies matters.
[1] U-Net: Convolutional Networks for Biomedical Image Segmentation, http://arxiv.org/abs/1505.04597
=> Add cropping to merge layers

docs/modules/layers.rst, docs/modules/layers/dense.rst, docs/modules/layers/special.rst, lasagne/layers/dense.py, lasagne/layers/special.py, lasagne/tests/layers/test_dense.py, lasagne/tests/layers/test_special.py
This moves `NonlinearityLayer` from `dense.py` to `special.py`, and adds a `BiasLayer`.
The implementation allows to specify which dimensions to share biases over. By default, it matches what the dense and convolutional layers do, so you can use the `BiasLayer` and `NonlinearityLayer` to pull out the bias and nonlinearity from a convolution layer over the following pooling layer for efficiency. I've also taken care to not create a fully-dimensional, broadcastable bias tensor, but to match the implementation of the dense and convolutional layers, which create a lower-dimensional tensor and dimshuffle it to the correct shape afterwards (i.e., in `get_output_for()`). This makes it even easier to steal an existing layer's bias and put it into a `BiasLayer`.
Resolves #378.
=> Add BiasLayer

lasagne/layers/recurrent.py, lasagne/tests/layers/test_recurrent.py
RecurrentLayer would throw an error when incoming was a tuple because it was trying to access incoming.output_shape.  This adds an explicit check whether incoming is a tuple, and handles it appropriately. Also adds a test for this special case because all of the RecurrentLayer tests used a InputLayer as incoming.
=> Fix RecurrentLayer type(incoming) == tuple error

docs/modules/layers.rst, docs/modules/layers/pool.rst, lasagne/layers/pool.py, lasagne/tests/layers/test_pool.py
Implemented Upscale2DLayer, a layer that performs in inverse operation of pooling layers.
Useful in segmentation approaches such as [1], [2] and [3].
The layer was added to pool.py. Tests are included.
[1] U-Net: Convolutional Networks for Biomedical Image Segmentation, http://arxiv.org/abs/1505.04597
[2] Hypercolumns for Object Segmentation and Fine-grained Localization, http://arxiv.org/abs/1411.5752
[3] Image Segmentation with Cascaded Hierarchical Models and Logistic
Disjunctive Normal Networks, http://www.cv-foundation.org/openaccess/content_iccv_2013/papers/Seyedhosseini_Image_Segmentation_with_2013_ICCV_paper.pdf
=> Implemented 2D upscaling layer

lasagne/layers/recurrent.py, lasagne/tests/layers/test_recurrent.py
Because of the way they are constructed, the weight matrices in a `RecurrentLayer` are both just called `layer_name.W` which is not terribly helpful.  This fixes that.  Are there any edge cases I'm not thinking of, e.g. would the `.name` attribute of the parameters ever not exist?
=> WIP: Give RecurrentLayer W params better names

docs/modules/layers.rst, docs/modules/layers/pool.rst, lasagne/layers/pool.py
I recently wanted to do mean pooling in one dimension.  I saw #320, but could not find something similar for only one dimension.  So I moved the functionality from MaxPool1DLayer to Pool1DLayer, and let MaxPool1DLayer inherit from Pool1DLayer in a similar way to how MaxPool2DLayer works.  Using `mode='average_exc_pad'` seems to be much slower than `mode='max'`, but this is probably to be expected.
If this is useful and correct, I'll go ahead and squash the commits.
=> Pool1DLayer

lasagne/layers/merge.py, lasagne/tests/layers/test_merge.py
As noticed in https://groups.google.com/forum/#!topic/lasagne-users/Zqrj1lSm9nc, `ConcatLayer` does not support `None`s in the concatenation axis. While solving this, I noticed that we're always basing the output shape on the input shape of the first incoming layer, which might have more (or different) unknowns than other incoming layers. I've addressed this as well, both for `ConcatLayer` and `MergeLayer`, by taking the maximum over all input sizes for each input dimension -- this conveniently replaces any `None`s with known values if there are any (we can do that because we know the input shapes have to match). This also allows us to add more thorough error checks. The improved shape propagation and error checking is covered by tests.
=> Correct variable shape propagation for merge layers

lasagne/layers/special.py, lasagne/tests/layers/test_special.py
This PR does a few things to the spatial transform layer:
* For consistency, it renames the `input` constructor argument to `incoming` and adapts the docstring accordingly
* Also for consistency, it changes the exception messages a little
* It drops the `deterministic=False` keyword argument from `get_output_for`, it was never used
* It allows `downscale_factor` to be a two-element tuple and adapts the docstring and tests accordingly
* ~~If the image size is known at compile time, it constructs the meshgrid offline instead of doing it symbolically~~
* Shape and coordinate casting is done in a better order to avoid needless device/host transfers
* The custom `_repeat` function is replaced by `T.repeat`
Unluckily, speed improvements were minuscule. I've got something between 1% and 4% both …
=> Optimize TransformerLayer

.travis.yml
Also remove use of Conda.  The new pip with a wheels cache should be
just as fast.
Gets rid of the Travis warning "This job ran on our legacy infrastructure..."
It's a work in progress because I still have to see that it's actually fast enough.
=> Migrate Travis config to container-based infrastructure.

docs/user/installation.rst
I've added information on the Docker images to the docs, which closes https://github.com/Lasagne/Lasagne/issues/411.
I have also successfully run the test suite on both CPU and CUDA containers without errors.
=> Add Docker images to docs

docs/conf.py, docs/user/installation.rst
This hopefully fixes #417 (and it fixes markup errors introduced in #412, so we're down to zero Sphinx warnings again).
=> Fix readthedocs build

README.rst
Does what it says. Make detecting https://github.com/Lasagne/Lasagne/issues/417 a little easier.
=> Fix Read the Docs badge

docs/conf.py
Reverts attempt in #419 to fix #417. It turned out the problem was a readthedocs misconfiguration, and the fix does not remove the need to install lasagne before building the documentation (it just makes the error message more cryptic -- a failed `import lasagne` hints more clearly at installing lasagne than [some `pkg_resources` error](https://github.com/Lasagne/Lasagne/pull/419#issuecomment-141085130)).
=> Revert unsuccessful attempt at fixing readthedocs build

lasagne/layers/shape.py, lasagne/tests/layers/test_shape.py
Fix a but where the SliceLayer would fail if one tried to slice a dimension with size None.
This would fail:
```Python
import lasagne
import theano.tensor as T
from lasagne.layers import *
import numpy as np
sym_x = T.matrix()
l_in = InputLayer((None, 10), sym_x)
l_slice = SliceLayer(l_in, axis=0, indices=slice(0, 50))
l_out = ConcatLayer([l_slice, l_slice], axis=0)
output = lasagne.layers.get_output(l_out)
print output.eval({sym_x :np.ones((100, 10), dtype='float32')}).shape
```
=> fix slicing axis with size None

docs/conf.py
Fixes #434. https://github.com/rtfd/readthedocs.org/pull/1693 restores compatibility with Sphinx 1.2 on readthedocs (we need to use 1.2 due to https://github.com/sphinx-doc/sphinx/issues/1822 which will only be fixed in 1.4), but only if `html_theme` is not set in `conf.py` when running on readthedocs. So we comply. (It doesn't make a difference when building the docs locally.)
Will merge this right away as I don't expect a fruitful discussion over four inserted blanks ;)
=> Fix documentation build after changes on readthedocs

docs/modules/objectives.rst, lasagne/objectives.py, lasagne/tests/test_objectives.py
We overlooked in #428 that it didn't add the new functions to the Sphinx docs. I'm doing this here, changing some bits and pieces for better consistency (including removal of the restrictions for the binary hinge loss and accuracy, to be consistent with the binary cross-entropy).
=> Add recently added objectives to docs; remove unnecessary restrictions

examples/mnist.py
I had a commented line in the MNIST example that shows how to save parameters. However, it inadvertently saved all the parameters as a single numpy array of dtype='O' that had all the other numpy arrays as its elements. Although it works, this was not what I meant to suggest to users.
This PR changes the commented line to save the parameters as separate arrays, and adds two more lines that show how to re-read them (in correct order).
=> MNIST example: Show how to save and load param values

docs/modules/nonlinearities.rst, lasagne/nonlinearities.py, lasagne/tests/test_nonlinearities.py
This extends PR #409 with better documentation (and correct markup) and slightly simplified code. If this is merged, it closes #409.
(I originally wanted to send @Botev a PR to his PR, but since no further work is required on top, I figured it would be easier to send a new PR to Lasagne instead.)
/edit: I also swapped the meaning of alpha and beta, since I found it extremely confusing that they were not matching the order of scale_in and scale_out in the constructor parameters. For a fact, Alexander got confused by this as well and reported LeCun's suggested factors in a different order than the other ones.
=> Scaled tanh nonlinearity

lasagne/layers/recurrent.py
Right now, to disable gradient clipping in recurrent layers, you need to set `grad_clipping=False`. This is tested for in the code via `grad_clipping is False`, so any other falseish value will not work. This PR changes the implementation to also have `grad_clipping=0` (or any falseish value) disable gradient clipping. Right now, `grad_clipping=0` completely disables backpropagation through the recurrent layer -- I don't think there's an important use case for this, and I know at least one person who would have expected `grad_clipping=0` to mean the same as `grad_clipping=False` and wondered why their networks wouldn't learn anything.
=> Recurrent layers: Also allow grad_clipping=0 to disable gradient clipping

lasagne/layers/special.py, lasagne/tests/layers/test_special.py
Fixes #442. While this passes through an image almost unchanged for the identity transform values [1, 0, 0, 0, 1, 0], there are still some discrepancies due to mapping coordinates from [0, size] to [-1, 1] and back. I'll try to fix this by changing the meshgrid to return coordinates in [0, size].
=> Correct handling of borders in TransformerLayer

lasagne/layers/recurrent.py
Fixes  #448: peepholes being added after outgate nonlin
=> Fix bug in LSTMLayer where peephole to outgate was added before nonlinearity

lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py
Currently the docs say that `pad='same'` will work for both odd and even `filter_size`, but this is not tested and fails on all implementation except `Conv2DLayer`.
I don't think this case is worth supporting:
1. It's not possible to avoid asymmetric edge effects
2. I think it's uncommon in practice
3. It requires ugly and inefficient code to support
Therefore, this PR raises `NotImplementedError` in all conv layers for this case. 
It also changes how `Conv1DLayer` implements same padding to avoid the slow compilation bug. 
This supersedes and will close https://github.com/Lasagne/Lasagne/pull/415 if merged.
=> Remove conv same pad for even filter_size

docs/modules/layers.rst, docs/modules/layers/pool.rst, lasagne/layers/pool.py, lasagne/tests/layers/test_pool.py
This adds Upscale1DLayer, based on the Upscale2DLayer implementation. I've trained with it and it seems to work correctly.
It would be nice to have something like UpscaleNDLayer with a mode parameter that could be 'nearest' (current behavior), 'bilinear', or something else, similar to Pool1DLayer or Pool2DLayer. Though I'm not sure if there is any literature supporting the possibility of other kinds of upscaling.
=> added Upscale1DLayer implementation

README.rst
Due to unsolved problems at Travis (https://github.com/travis-ci/travis-ci/issues/4024#issuecomment-146899985), the Travis badge displays "build: failing" while in fact it's fine. Removing `branch=master` from the badge link circumvents this. Fixes #458.
=> Circumvent Travis badge bug

lasagne/__init__.py
This adds an additional check to `__init__.py` to not only test whether Theano is importable, but also test whether it is recent enough to support what's needed by Lasagne. The most recent feature we actually use is `theano.tensor.nnet.relu`. There are some commits between the addition of that feature to Theano and the commit we've got in our `requirements.txt`, but it's unlikely that anybody uses this and even if so, it wouldn't cause any problems -- the main goal is to catch users who merely installed the latest Theano release.
Corrects the link to the installation instructions, and clarifies that `pip install theano` is not the solution.
This closes #454.
=> Check that Theano is recent enough

lasagne/layers/base.py, lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dense.py, lasagne/layers/dnn.py, lasagne/layers/embedding.py, lasagne/layers/helper.py, lasagne/layers/special.py, lasagne/tests/layers/test_base.py, lasagne/tests/test_updates.py, lasagne/tests/test_utils.py, lasagne/updates.py, lasagne/utils.py
First stab at #11, to continue the discussion based on actual code.
This gets the basic case working:
```
In [3]: l1 = lasagne.layers.DenseLayer((100, 10), 20)
In [4]: l2 = lasagne.layers.DenseLayer(l1, 10, W=l1.W.T)
In [5]: lasagne.layers.get_all_params(l2)
Out[5]: [b, W, b]
In [6]: l1.params
Out[6]: OrderedDict([(W, set(['trainable', 'regularizable'])), (b, set(['trainable']))])
In [7]: l2.params
Out[7]: OrderedDict([(W.T, set(['trainable', 'regularizable'])), (b, set(['trainable']))])
```
It will work just as fine with `T.exp(l1.W)`, something adding up two shared variables, or something involving no shared variables at all (e.g., a constant weight matrix).
If there are no objections to the way it's implemented, I can go ahead and update the documentation and tests, as well as the …
=> Allow arbitrary parameter expressions

examples/mnist.py
mnist.py expects the first command line argument to the a model
name. If the model isn't recognised there is an UnboundedLocal
error as `network` is used before assignment.
Since there's nothing that can be done in this case, exit with
error letting the user pick a valid model.
=> mnist.py: Exit with error when model name isn't recognised.

examples/recurrent.py
As pointed out here:
https://groups.google.com/d/msg/lasagne-users/MrDuFJy4qNg/1PUs1PPRDQAJ
the recurrent example was using a slice which was effectively turning the 2D output (with the final dimension being 1) into a 1D output.  This was a holdover from when we used to not use `SliceLayer`s in the recurrent example.  It makes more sense (to me) to use a `flatten`, and I've fixed the comment to describe what's actually going on.
=> Clarify recurrent example output flattening

lasagne/__init__.py, setup.py
Instead of using `pkg_resources.get_distribution()` to set `lasagne.__version__` to whatever version of Lasagne is currently installed, this PR hard-codes `lasagne.__version__` to a plain string and reads that string from `setup.py` to avoid maintaining it in two places.
Resolves #477, closes #478.
The less adventurous alternative would be hard-coding it both in `__init__.py` and in `setup.py`. Any preference?
=> Avoid dependency on pkg_resources for lasagne.__version__

docs/modules/layers.rst, docs/modules/layers/special.rst, lasagne/layers/special.py, lasagne/tests/layers/test_special.py
This provides some boilerplate to make it easier to apply simple operations without needing to define a custom Layer class. There's been a few occasions where I think this could be useful, most recently https://github.com/Lasagne/Lasagne/issues/440.
Since everyone loves a good naming discussion, `LambdaLayer` is probably not that great, since using a lambda expression is optional... `FunctionLayer` or `ExpressionLayer` are my other ideas.
=> add LambdaLayer

examples/recurrent.py, lasagne/layers/recurrent.py, lasagne/tests/layers/test_recurrent.py
Resolves #471.  I opted for `return_final`; it has the same meaning as `only_return_final` but is shorter to type.
=> Add kwarg to recurrent layers to return only final output

lasagne/updates.py
There appeared to be a minor error. Before the change, the equations for r_t and s_t were identical.
=> fix adadelta docs for moving average of update

docs/modules/layers.rst, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py
This adds a `Conv3DDNNLayer` class for cuDNN-based 3D convolution. It also refactors the convolution tests to reduce some of the code duplication in setting up the test cases (there's still a lot of duplication, but that's harder to tackle).
In a follow-up PR, I'd like to refactor all convolutional layers (all dimensionalities and all implementations) to be derived from a common `BaseConvLayer` that contains most of the code. This will make it much easier to add additional checks such as matching input and convolution dimensionality.
=> Add Conv3DDNNLayer

lasagne/layers/shape.py, lasagne/tests/layers/test_shape.py
This makes it so that the `PadLayer` can accept shapes with `None` in them past their "batch" dimension, e.g.
```Python
import numpy as np
import lasagne
input_shape = (None, 3, None, 40)
dummy_input = np.random.standard_normal((100, 3, 30, 40)).astype(theano.config.floatX)
l_in = lasagne.layers.InputLayer(input_shape)
l_pad = lasagne.layers.PadLayer(l_in, width=4)
l_conv = lasagne.layers.Conv2DLayer(l_pad, 16, (3, 3))
print lasagne.layers.get_output(l_conv).eval({l_in.input_var: dummy_input}).shape
```
Without this change, this would result in 
```Python
lasagne/layers/shape.py in get_output_shape_for(self, input_shape)
327             except TypeError:
328                 l = r = w
--> 329             output_shape[k + self.batch_ndim] += l + r
330         return tuple(output_shape)
331 …
```
=> Allow PadLayer to accept None dimensions

lasagne/layers/input.py, lasagne/tests/layers/test_input.py
Fix https://github.com/Lasagne/Lasagne/issues/457
Add test for negative shape in input Layer. 
The `str(name)` is a bit ugly but the inputLayer might have a `None` name as far as i read the code?
=> add negative shape check to inputLayer

docs/modules/nonlinearities.rst, lasagne/nonlinearities.py, lasagne/tests/test_nonlinearities.py
Adds the exponential linear unit (http://arxiv.org/abs/1511.07289).
Note: This isn't optimized for performance yet. It's possible that there's a way to express it more efficiently in Theano, but for optimum performance this may need to be implemented as a Theano Op.
=> Add Exponential Linear Unit (ELU)

docs/modules/utils.rst
Noticed they were missing. My bad (#404)!
=> Add collect_shared_vars() to Sphinx docs

lasagne/updates.py
#211 changed the docstring of nesterov_momentum() to something wrong. This PR undoes the change. Closes #527.
=> Fix docstring for nesterov_momentum()

lasagne/layers/recurrent.py, lasagne/tests/layers/test_recurrent.py
I have added an optional incoming layer `prefill_h` to the GRULayer so that it can be used as part of an encoder-decoder model. It should not be difficult to do this for the other recurrent layers. Also included is a simple example of its usage.
I have been using this approach in my own work and thought it worth feeding back into the project.
Closes #462.
=> Fill the initial hidden state of GRULayer with output from a previous layer

lasagne/__init__.py, lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py, lasagne/tests/test_theano_extensions.py, lasagne/theano_extensions/conv.py, requirements.txt
Starting to address #524. First two commits:
* Add a `BaseConvLayer` class that has all the common code and derive all other convolutional layer implementations from that. Was pretty easy except for all the special-casing in `Conv2DCCLayer`: It has a `dimshuffle` argument that optionally makes it operate directly on data in c01b layout, and it stored `self.filter_size`, `self.pad` etc. as a single integer despite being a 2D layer. I had to change the latter because I couldn't call the super constructor otherwise, also I think it's better to be consistent with other layers.
* Added a check to `BaseConvLayer` to test whether the input dimensionality fits the convolution dimensionality. There were some reports on the mailing list about users getting this wrong and getting …
=> Revamp Convolutional Layers

lasagne/tests/test_updates.py, lasagne/updates.py
This is an implementation of Adamax, a variant of Adam described in the latest version of the paper ( http://arxiv.org/abs/1412.6980 ) which uses the inifinity norm instead of the L2 norm. This is argued to be more stable in the case of sparse updates (e.g. for embeddings).
I have not included tests yet since I noticed that the existing updates implementations are all tested against a Torch implementation. @ebenolson, I believe you set this up, so it would be great if you could chime in :) We may want to include a separate set of tests that do not depend on Torch, so that it's easier to add new update rules.
=> Adamax updates

lasagne/layers/merge.py, lasagne/tests/layers/test_merge.py
Adds a test to PR https://github.com/Lasagne/Lasagne/pull/552. PR https://github.com/Lasagne/Lasagne/pull/552 fixes issue https://github.com/Lasagne/Lasagne/issues/551.
Fixes #551, closes #552, closes #517.
1) replace ndim with len(inputs) in line 119
2) test that the number of outputs is correct when the number of inputs
is larger than ndim of the inputs.
=> replace ndim with len(inputs) in line 119 + test

lasagne/layers/recurrent.py, lasagne/tests/layers/test_recurrent.py
Removes TensorVariable special case as discussed here: https://github.com/Lasagne/Lasagne/issues/462
* Removes TensorVariable Init.
* Removes related Tests
=> Remove TensorVariable Init

lasagne/layers/recurrent.py
Replace masked code in all recurrent layers by T.switch command
Closes #550.
=> Replace masked code in all recurrent layers by T.switch command

docs/modules/layers.rst, docs/modules/layers/normalization.rst, lasagne/layers/normalization.py, lasagne/tests/layers/test_normalization.py
Finally started integrating my batch normalization implementation in Lasagne. Changes from [the implementation in my gist](https://gist.github.com/f0k/f1a6bd3c8585c400c190):
* Adding epsilon before taking the square root of the variance
* Change parameters to have reduced dimensionality rather than broadcastable singleton dimensions, to match with `BiasLayer` (which in turn was made to match `DenseLayer`, `Conv2DLayer` etc.)
TODO:
Resolves #141.
=> Add BatchNormLayer

lasagne/utils.py
Probably it doesn't matter much since this function is only used in get_all_params.
=> don't use O(N^2) algorithm in lasagne.utils.unique

docs/modules/layers/special.rst, lasagne/layers/special.py, lasagne/tests/layers/test_special.py
The motivation behind this layer is this: Usually, part of your ML pipeline is to compute some statistics on the training set (mean and standard deviation, or min and max) and then use them to normalize/standardize all inputs to the network.  Currently, this needs to be done "outside of the model", i.e. when you save your model you must also save the training set statistics to use later when passing data through the model.  There's no convenient way to store this information in the model itself.  This layer simply stores these statistics, and then applies them in `get_output` in a smart way which hopefully covers most use-cases.  See the example in the docstring for an example.
As another (personally relevant) example, say you are passing sequences of feature tensors into a convolutional …
=> Add ScaleLayer and standardize function

lasagne/layers/special.py
=> Make shared_axes default to 'auto' in standardize

lasagne/layers/helper.py
`sum` allocates space for all the intermediary lists. For timings, see [this post](http://stackoverflow.com/questions/952914/making-a-flat-list-out-of-list-of-lists-in-python/952952#952952) on StackOverflow.
=> don't use O(N^2) algorithm in get_all_params

lasagne/layers/special.py, lasagne/tests/layers/test_special.py
Using `T.inv` with `type(scale) = np.ndarray` resulted in `scales` not being returned by `get_all_params` because it would be converted to a Theano constant, not a shared variable, so `collect_all_shared` missed it.  Here, I've changed to `utils.floatX(1.)/scale` instead.  This means `standardize` can't accept Theano expressions, which is fine, that is sort of a crazy use-case for the intended purpose.  I also added a simple additional test to make sure the problem is fixed.  Should resolve #583
=> Don't use T.inv in standardize

lasagne/tests/test_utils.py, lasagne/utils.py
Hi, 
I modified the compute_norms function to accept theano variables as well.
Also, 1D input is also supported, which would result in giving simple the abs value (just for convenience's sake)
The comments are updated as well as the test routine.
Closes #573.
Thanks,
Kwang
=> Issue #573 Theano tensor support for compute_norms

lasagne/layers/base.py, lasagne/layers/helper.py, lasagne/layers/normalization.py, lasagne/tests/layers/test_helper.py, lasagne/tests/layers/test_recurrent.py
This resolves issue #557. `get_output()` uses introspection to retrieve the key word arguments from `get_output_for()`. All layers now have the attribute `get_output_kwargs`, which allows a user to explicitly specify the kwargs `get_output_for` will use. Also, I changed the signature of `BatchNormalizationLayer.get_output_for` to explicitly state the kwargs that it uses.
=> Raise a warning when a keyword passed to `get_output()` is unused

lasagne/tests/layers/test_recurrent.py
I have written test cases for Recurrent, LSTM and GRU layers which pass some dummy inputs through `hid_init` (and cell_init where applicable) as a Layer and check the output. Essentially I check that you get the same result from passing a dummy input as an InputLayer and a np.array.
The need for this sort of test case was mentioned in PR #522
=> Additional test cases for hid_init as a Layer in recurrent layers.

lasagne/layers/noise.py, lasagne/tests/layers/test_noise.py
=> Dropout layer output type should match input type when rescale is False

docs/conf.py, lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py
Closes #379 by replacing `theano.config.device.startswith("gpu")` with `theano.sandbox.cuda.cuda_enabled`. This allows CUDA to be enabled in a script via `theano.sandbox.cuda.use("gpu0")` instead of only via the Theano configuration.
While we're at it, this changes the import error messages to point at the corresponding documentation on readthedocs.
=> Change GPU check to allow theano.sandbox.cuda.use()

lasagne/layers/normalization.py
My bad. At some point during development, `BatchNormLayer` had a `mode` argument. It was inadvertently left in the constructor when removing it from the implementation.
=> Remove forgotten `mode` argument from BatchNormLayer constructor

docs/user/tutorial.rst
The [Theano Tutorial](http://deeplearning.net/software/theano/tutorial/) has changed: The "Graph Structures" part has been moved from right after "More Examples" to "Further Readings" near the very end. As we asked people to read up to "Graph Structures", this means they'd now have to read basically everything. I'd change this to suggest to read up to "More Examples".
=> Update to reflect changes in Theano Tutorial

lasagne/__init__.py, lasagne/layers/pool.py, requirements.txt
Probably a good idea to update to the new Theano release.
The dependency check in `__init__.py` just checks for the new "feature" we use, which is the new name and location for the `max_pool_2d` function. We don't actually require a more recent Theano version than the one that introduced this. Is that okay? Any arguments against that?
=> Update Theano dependency to 0.8.0

docs/modules/layers/corrmm.rst, docs/modules/layers/cuda_convnet.rst, docs/modules/layers/dnn.rst
Closes the last TODO item of #524.
=> Document that corrmm, cuda_convnet and dnn layers need explicit imports

lasagne/layers/base.py, lasagne/tests/layers/test_base.py
=> Have `output_shape` property error out for symbolic shapes

lasagne/layers/noise.py, lasagne/tests/layers/test_noise.py, lasagne/tests/test_updates.py, lasagne/updates.py
These changes fix the upcasting issue in lasagne.update functions rmsprop, adadelta, adam and adamax where float32 inputs are given float64 updates 
A test method, test_update_returntype has also been added to the class TestUpdateFunctions which checks for this error.
Closes #402. Closes #563. Closes #578.
=> Fix lasagne updates

docs/modules/layers.rst, lasagne/layers/dnn.py, lasagne/tests/layers/test_pool.py
Hi everyone,
This PR would include spatial pyramid pooling following reference http://arxiv.org/abs/1406.4729.
The SpatialPyramidPoolingLayer will reduce the output of the convolutional/pooling part of a DNN to a fixed size independent of the original image dimension. Hence, a dense network structure with a fixed number of nodes may be added even though the input dimension is undetermined.
This implementation allows for any level of pooling (the paper uses 3-level and 4-level structures, but in principle it is arbitrary). All this is possible because dnn.dnn_pool can now take Theano expressions as input (https://github.com/Theano/Theano/pull/3965).
I hope this is of interest. 
best,
Philipp
=> Spatial Pyramid Pooling

lasagne/layers/normalization.py, lasagne/tests/layers/test_normalization.py
Closes #670.
Using suffixes '_bn' and '_bn_nonlin' (rather than just '_nonlin' for consistency w.r.t. case where BN layer is named through kwargs) for `BatchNormLayer` and `NonlinearityLayer` respectively.
Did not modify the docstring to mention this behavior.
=> Name layers created using batch_norm() utility

lasagne/layers/dnn.py, lasagne/tests/layers/test_pool.py
Follow-up to #650, which produced output data not matching the reported output shape (batchsize, channels * features) vs. (batchsize, channels, features), see https://github.com/Lasagne/Lasagne/pull/650/files#r61360880. Changed the layer to return (batchsize, channels, features) and extended the tests to ensure the returned data shape matches the computed output shape.
Thanks to @kli-nlpr for reporting it!
=> Fix SpatialPyramidPoolingDNNLayer mismatch between output shape and data

docs/modules/layers.rst, docs/modules/layers/conv.rst, lasagne/layers/conv.py, lasagne/tests/layers/test_conv.py
This adds a dilated convolution layer (as used in http://arxiv.org/abs/1511.07122). For the implementation, it uses the backward pass wrt. weights, using the fact that the convolution backward passes already support implicit dilation of the gradient wrt. output. By providing the weights as the output gradient and the input as the input, the convolution backward pass wrt. weights computes the dilated correlation we want.
The only caveat of this implementation is that we cannot support padding (it would pad the filters, resulting in cropped output) or filter flipping (it would flip the input, resulting in flipped output).
Performance-wise, another downside of the implementation is that we need to transpose the input and output, swapping batch size and channels.
An alternative implementation …
=> Add DilatedConv2DLayer

lasagne/layers/base.py, lasagne/layers/helper.py, lasagne/tests/layers/test_helper.py
This PR fixes #641. It adds the ability to make get_params and get_all_params return Theano expressions if any of the parameters was registered as a Theano expression. To this end this PR adds the keyword *unwrap_shared* (default: True) to both methods. The default behaviour of both methods is unchanged, yet setting unwrap_shared=False will yield the Theano expressions instead of the contained shared variables.
=> Extending get_params to optionally return Theano expressions

lasagne/tests/layers/test_special.py
Two of the RandomizedRectifierLayer tests used the fact that T.nnet.relu() worked both with symbolic expressions and with numpy arrays. With Theano/Theano/pull/4484, it always returns a symbolic expression. This updates the tests in Lasagne to work with Theano versions both before and after this change.
=> Update RReLU tests for updated T.nnet.relu function

examples/mnist.py
Fix iterate_minibatches function in case nb of inputs < batchsize, if nb inputs < batchsize it does not iterate through available inputs, I know it does not make sense to have nb inputs < batchsize but it should do the correct thing if it is.
=> Clarifying comment for iterate_minibatches in mnist example

docs/user/installation.rst
The CUDA Docker images are moving to use the NVIDIA Docker program, so I've updated the docs appropriately.
=> Update Docker instructions

lasagne/tests/test_utils.py, lasagne/utils.py
This issues comments raised in https://github.com/Lasagne/Lasagne/issues/693
=> Make lasagne.utils.create_param() get callable that returns Theano expressions or shared variables

lasagne/tests/test_utils.py, lasagne/utils.py
This PR makes create_param() set the broadcast pattern when creating a shared variable. We assume our network parameters never change shape, so we can at least fix the broadcast pattern (shared variables don't allow setting a fixed shape). This saves some headaches when users have a DenseLayer of 1 unit and try to do something fancy with the output (as here: https://groups.google.com/d/msg/lasagne-users/MQfjYI-tV2I/pf-z_NnyBQAJ), since now Theano can infer that the output is broadcastable on the last axis.
=> Have create_param() set the broadcast pattern

lasagne/layers/merge.py, lasagne/tests/layers/test_merge.py
Fixes #723 by allowing negative axes in `lasagne.layers.ConcatLayer`. Specifically, the shape matching check in `get_output_shape_for()` had to be changed.
=> Support negative axis in ConcatLayer

lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py
The incoming dimensions were in the wrong order. Looked around and found the correct order [in a recipe](https://github.com/Lasagne/Recipes/blob/master/modelzoo/c3d.py) and [in the Theano source](https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/dnn.py#L1201).
=> Updated docs for Conv3DDNNLayer

lasagne/layers/special.py
The TestTransformLayer.test_transform_affine_identity and TestTPSTransformLayer.test_transform_thin_plate_spline_variable_input tests were  failing on my machine due to my .theanorc file:
```
[global]
...
int_division = raise
...
```
They both raised this theano error:
```
raise IntegerDivisionError(
>                   "With `config.int_division` set to 'raise', dividing two "
"integer types with '/' is forbidden to avoid confusion "
"between integer and floating point divisions. Please "
"use // for integer division, or if you want a float result "
"either cast one of the arguments to a float or directly call "
E                   IntegerDivisionError: With `config.int_division` set to 'raise', dividing two integer types with '/' is forbidden to avoid confusion between integer and …
```
=> Fixed theano error on truedivision of integers

lasagne/layers/merge.py, lasagne/tests/layers/test_merge.py
Fixes #674
This fixes the issue with calculating crop shapes in Python 3 for merge layers with `None` somewhere in their shape. The additional test case passes in Python 2.7 and 3.4. Without the fix it will pass in 2.7 but fail in 3.4, as described in #674.
=> Fixed auto_crop_array_shapes for python3 when shape contains None.

docs/modules/layers.rst
`ScaleLayer`, `standardize` and `TPSTransformerLayer` are listed in `doc/layers/special.rst`, but were missing from `doc/layers.rst`.
=> Add missing layers to layer overview

docs/modules/layers.rst, docs/modules/layers/noise.rst, lasagne/layers/noise.py, lasagne/tests/layers/test_noise.py
This adds a `shared_axes` argument to the DropoutLayer, to support tied dropout masks. It also adds convenience functions `dropout_channels`, `dropout_locations` and `spatial_dropout` as an alias for `dropout_channels`. Before adding the argument, I also partly rewrote the DropoutLayer docstring, to better explain the role of `rescale` and `deterministic`.
Closes #710, closes #701.
=> Add `shared_axes` argument to DropoutLayer

docs/modules/layers.rst, lasagne/layers/dnn.py, lasagne/tests/layers/test_normalization.py
This adds `lasagne.layers.dnn.BatchNormDNNLayer` and `batch_norm_dnn`, as drop-in replacements for the ordinary batch normalization layers. They improve training performance a lot over the vanilla Theano layers, and also reduce memory usage. For a 40-layer DenseNet, I observed speed improvements of 25% to 35% depending on the GPU. Closes #743.
cuDNN-based batch normalization currently requires the bleeding-edge version of Theano (specifically, after this PR: https://github.com/Theano/Theano/pull/4582). If the Theano version is too old, both the class and the convenience function are deleted from `lasagne.layers.dnn`. This allows for easy compatibility in user code such as:
```python
try:
from lasagne.layers.dnn import batch_norm_dnn as batch_norm
except ImportError:
from lasagne.layers …
```
=> Add BatchNormDNNLayer and convenience function

lasagne/layers/dense.py, lasagne/tests/layers/test_dense.py, lasagne/tests/test_regularization.py
As proposed in #719, this adds a `leading_axes` argument to `DenseLayer` which allows to specify how many axes of the input tensor should be treated as leading axes, only collapsing the remaining axes for the matrix product. For example, with `leading_axes=2`, this corresponds to the time-distributed dense layer of Keras.
I've slightly changed the dense layer tests to use a parameterized fixture, so existing tests run with different settings for `leading_axes`.
I've also added a check to the constructor to give a meaningful error if any trailing axes have an unspecified size. Before, it would just run into an exception in `np.prod`.
Closes #719.
=> Add num_leading_axes argument to DenseLayer

lasagne/objectives.py, lasagne/tests/test_objectives.py
This changes behaviour of lasagne.objectives.* for a special case: If predictions are a column vector (i.e., a matrix that is broadcastable in the second dimension) and targets are a 1D vector, implicitly turn the targets into a column vector as well. This avoids the current trap (opened in #715) that combining a network with a single output unit and a T.vector() target broadcasts predictions and targets to compare all predictions against all targets. Closes #755, but we need to discuss whether we want this. I'd argue that it seems so natural to use T.vector() for regression or binary classification targets that we should just support it. The alternative would be to warn the user to use a T.matrix() or T.col() instead.
Trapped users: …
=> Allow vector targets for column vector predictions in objectives

lasagne/objectives.py, lasagne/tests/test_objectives.py
The `binary_hinge_loss` looks like it would be a drop-in replacement for `binary_crossentropy`, but it isn't: It requires the log odds of the network predictions (i.e., the sigmoid input, not the sigmoid output). This PR documents this and adds a `log_odds` argument. Similar to the existing `binary` argument which allows using the objective both with 0/1 and +/-1 targets, it allows to use the objective both with sigmoid outputs and sigmoid inputs. Closes #744.
=> binary hinge loss: Add log_odds argument

lasagne/layers/recurrent.py, lasagne/tests/layers/test_recurrent.py
Fixes #730. For LSTM and GRU layers with num_units=1, the broadcast pattern of `outputs_info` in `theano.scan()` did not match the broadcast pattern of what was returned by the inner loop function. In particular, slicing a tensor `x[:, n*num_units:(n+1)*num_units]` does not allow Theano to infer that the second dimension is broadcastable, but the dot products against the input-to-hidden, hidden-to-hidden and cell update matrices in the inner loop function do allow Theano to infer the broadcast pattern, creating a mismatch.
This PR solves this by adding an explicit `T.add_broadcast` for `num_units=1` (and adds tests to verify that it works).
=> Correct broadcast patterns for recurrent layers with num_units=1

lasagne/layers/local.py, lasagne/tests/layers/test_local.py
The ```j = self.filter_size[0] // 2``` in the initial case of ii == jj == 0 in convolve should be ```j = self.filter_size[1] // 2```.
Before submitting your pull request, please check these hints!
- If you are not familiar with the github workflow, have a look:
https://guides.github.com/introduction/flow/
In particular, note that in order to update your pull request to include any
changes we asked for, you just need to push to your branch again.
- If your pull request addresses a particular issue from our issue tracker,
reference it in your pull request description on github (not the commit
message) using the syntax `Closes #123` or `Fixes #123`.
Pull request check list:
- Install Lasagne in editable mode to be able to run tests locally: …
=> Fix locally-connected layer for non-square filters

lasagne/layers/input.py, lasagne/tests/layers/test_input.py
A colleague ran into a problem with a recurrent layer not giving the correct broadcast pattern in the output of the scan's step function. Investigating, the problem turned out that an `InputLayer` of shape `(None, None, 1)` still assigns a broadcast pattern of `(False, False, False)` to the `input_var` automatically created in the constructor.
This PR creates the input variable with the broadcast pattern inferred from the input shape.
=> Infer broadcast pattern for InputLayer.input_var.

lasagne/layers/helper.py, lasagne/tests/layers/test_helper.py, lasagne/tests/test_utils.py, lasagne/utils.py
This comes from Debian packaging, the test failed building on Python 3.5 (<https://bugs.debian.org/834910>). The patch is written by Ole Streicher.
Best,
DS
=> use inspect.signature instead of inspect.getargspec if possible

docs/modules/layers.rst, docs/modules/layers/pool.rst, lasagne/layers/pool.py, lasagne/tests/layers/test_pool.py
This pool request addresses issue #681. 
It implements the layer lasagne.layers.pool.SpatialPyramidPoolingLayer. This layer includes both the same functionality as dnn.SpatialPyramidPoolingDNNLayer (without relying on cudnn), and adds a new mode (mode='kaiming') that implements the pooling operation as described in the original paper [1]. This new mode resolves #681, and works with any input size. However, this implementation is slower since it does not use pool_2d, and instead manually slices the input and compute the max of the regions (which may not be a big overhead, given that the number of output "bins" is usually small: 21 in the default implementation). 
Since it is slower, and also to keep the same functionality as the dnn version, it is not the default mode.
[1] He, Kaiming et …
=> Implement SpatialPyramidPooling without cuDNN; new mode='kaiming'. Addresses #681

docs/conf.py, docs/modules/layers.rst, docs/modules/layers/conv.rst, docs/modules/layers/pool.rst, lasagne/layers/conv.py, lasagne/layers/pool.py, lasagne/tests/layers/test_conv.py, lasagne/tests/layers/test_pool.py
Hi everyone
I finally I got to do this overdue PR.  Closes #27.
Currently only works with the development version of Theano, which provides the necessary functionality.
For the tests I adapted them from the DNN versions.
I saw that the default for flip_filters in the conv.py is True, but for the convs in dnn.py it is False. Is there a reason for that? Might lead to some confusion!
Thanks for feedback & Cheers,
Michael
=> Generic 3D conv layer and 3D pool layer

lasagne/updates.py
This updates the lasagne.updates module docstring with an example on using shared variables for the learning rate. Furthermore, it updates the adam and adamax docstrings to accept symbolic scalars for hyperparameters, just like all the other optimization schemes.
Closes #810.
=> Document shared variables for optimization hyperparameters

lasagne/nonlinearities.py, lasagne/tests/test_nonlinearities.py
expm1(x) is equivalent to exp(x)-1 but should be more stable since the calculation can be more precise. Available since Theano 0.6rc1 (Oct 2012).
=> Make use of expm1() to implement ELU

README.rst
It's not easy to see how to cite Lasagne. Adding a BibTeX entry directly to the README is not ideal: When we release a new version, its README would still have the BibTeX entry for the previous version (since we only get a new Zenodo reference *after* a release). To circumvent this, I've added a BibTeX entry to the wiki and link to it from the README.
Closes #73.
=> Add link on citing Lasagne

lasagne/layers/special.py, lasagne/tests/layers/test_special.py
Closes #689.  Add additional border modes for _interpolate to be consistent with scipy.
=> Additional border_modes for _interpolate.

lasagne/layers/special.py, lasagne/tests/layers/test_special.py
Follow-up to #793: Moves handling the border modes until after conversion to pixel space, so they are also respected in interpolation.
@hjweide: I'm a bit puzzled by the `0.5` in `mirror` mode (see the test). Any idea?
=> Handle spatial transformer border modes in pixel space

lasagne/layers/corrmm.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py, lasagne/tests/layers/test_noise.py, lasagne/tests/layers/test_special.py
This PR is a first attempt to fix #698, I have not added the fix for sphinx yet.
=> fixes for support of new backend

docs/conf.py
With #836, the GPU backend checks have changed. The sphinx configuration needs to be adapted such that we can still build the full documentation regardless of the Theano version and device configuration.
=> Adapt sphinx configuration to modified GPU backend checks

lasagne/layers/corrmm.py, lasagne/layers/cuda_convnet.py, lasagne/layers/dnn.py
Fixes #706. A warning is added to 3 gpu modules: lasagne.layers.dnn, lasagne.layers.corrmm and lasagne.layers.cuda_convnet. So when ```floatX=float64``` and one of them is imported, the user is warned that cuda array only supports float32 and they should switch to it. We can also change ```floatX``` to ```float32``` automatically and do this favor for the user :D 
What do you think?
=> add warning for float64 in gpu layer modules

lasagne/layers/helper.py, lasagne/tests/layers/test_helper.py
Fixes https://github.com/Lasagne/Lasagne/issues/773. I think I will still need to add tests for coverage.
=> added check for input.key() to be layer instance

lasagne/layers/noise.py, lasagne/tests/layers/test_noise.py
=> Fixed float16 error wrt Theano=0.8.2

lasagne/objectives.py
=> Added required doc for categorical cross entropy

lasagne/layers/cuda_convnet.py
Fixes #866. Closes #882 (which had the check wrong).
=> Better error message when importing cuda_convnet under new GPU backend

lasagne/layers/normalization.py, lasagne/tests/layers/test_normalization.py
=> Added tag "bn_stat" to mean and inv_std params

docs/modules/objectives.rst, lasagne/objectives.py, lasagne/tests/test_objectives.py
=> Added Huber loss

docs/modules/updates.rst, lasagne/tests/test_updates.py, lasagne/updates.py
This is an implementation of the AMSGrad algorithm as suggested in https://openreview.net/forum?id=ryQu7f-RZ
I don't have any tests for this. It seems that the existing algorithms in Lasagne just check against the Torch implementations. Suggestions?
=> Implemented amsgrad updates

lasagne/layers/conv.py, lasagne/layers/corrmm.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py, lasagne/tests/layers/test_local.py, lasagne/theano_extensions/conv.py
Adds support for grouped convolutions in the `Conv*DLayer` classes, along with tests, usable only with Theano 0.10 and above (a proper error message is given for older Theano versions).
Dilated and transposed convolutions should support groups as well, but this can wait until after #716 and #850, respectively.
=> Support grouped convolutions

lasagne/layers/corrmm.py, lasagne/layers/dnn.py, lasagne/tests/layers/test_conv.py
At some point after removing `theano.sandbox.cuda`, Theano opted to raise a `nose.SkipTest` exception instead of an `ImportError` when trying to import it. Some checks in Lasagne were still expecting an `ImportError` when `theano.sandbox.cuda` was not available. To avoid introducing a dependency on `nose`, this PR changes those checks to catch a generic `Exception`. This might mask other exceptions for users of Theano 0.8/0.9 trying to get CUDA to run, but avoids misleading exceptions for users of Theano 0.10. Seems that's the best we can do (without introducing a dependency on `nose` or checking the exception class name).
=> Catch exception by Theano 0.10+ on importing theano.sandbox.cuda

docs/modules/utils.rst, lasagne/layers/conv.py, lasagne/layers/normalization.py, lasagne/layers/shape.py, lasagne/layers/special.py, lasagne/tests/layers/test_conv.py, lasagne/tests/test_utils.py, lasagne/theano_extensions/conv.py, lasagne/theano_extensions/padding.py, lasagne/utils.py
In a couple of places, Lasagne has `isinstance(..., int)` checks. Those will fail for a `long` in Python 2 (which appear in `ndarray.shape` under Windows), and for `np.int64` in Python 3 (which appear in `np.prod(ndarray.shape)`, for example). A generic type check that works both in Python 2 and 3 is `isinstance(x, (numbers.Integral, np.integer))`.
This PR adds `lasagne.utils.int_types`, a tuple of `numbers.Integral, np.integer`, and uses it instead of `int` where appropriate. It also extends `lasagne.utils.as_tuple` to allow a type tuple instead of a single type.
Fixes #847.
=> Properly handle integral types other than plain int

docs/modules/layers.rst, docs/modules/layers/normalization.rst, lasagne/layers/normalization.py, lasagne/tests/layers/test_normalization.py
Added a layer called 'InstanceNormLayer' that implements instance normalization of its inputs as according to 'Instance Normalization: The Missing Ingredient for Fast Stylization'      (https://arxiv.org/pdf/1607.08022.pdf).
While the existing BatchNormLayer is able to implement instance normalization by setting the axes, beta and gamma arguments accordingly, it still requires a fixed batch size as learned parameters need to be initialized. 
The proposed InstanceNormLayer gets away with that, allowing for more flexibility.
=> Implementation of Instance Normalization
