lasagne/layers/__init__.py
lasagne/layers/dnn.py

This needs some tests, but I don't have access to a machine with cudnn installed at the moment. Hopefully I'll get around to it shortly.

[WIP] add pooling layer based on dnn_pool, to support strided pooling

---

examples/mnist.py
lasagne/objectives.py

Implemented negative-log-likelihood objective function in objectives module.
Modified MNIST example to use it.
Also (accidentally) included a modification to the MNIST example that prevents it from re-downloading the dataset each time it is run.

Negative-log-likelihood objective function.

---

examples/mnist.py
lasagne/utils.py

Moving these unrelated parts out of the py2/3 effort (#119)

Mnist redownload check, dtype for shared_empty

---

lasagne/layers/base.py
lasagne/layers/conv.py
lasagne/layers/corrmm.py
lasagne/layers/cuda_convnet.py
lasagne/layers/dense.py
lasagne/layers/dnn.py
lasagne/layers/input.py
lasagne/layers/merge.py
lasagne/layers/noise.py
lasagne/layers/pool.py
lasagne/layers/shape.py
lasagne/tests/layers/test_base.py
lasagne/tests/layers/test_dense.py
lasagne/tests/layers/test_input.py

naming layers

---

lasagne/theano_extensions/conv.py

fixes bordermode full and same not being passed to T.nnet.conv2d

fix bordermode conv1d

---

lasagne/layers/shape.py
lasagne/tests/layers/test_shape.py

Implemented DimShuffleLayer in lasagne.layers.shape. Implemented tests.

DimShuffle layer

---

examples/mnist.py
examples/mnist_conv_cc.py
examples/mnist_conv_dnn.py

Changes:
- fix dnn imports in the examples
- cuda-convnet example didn't return output_layer
- the accuracy returned was float64, which caused problems when the warn_float64 theano flag is set

Fix examples

---

requirements.txt

Doing this as a PR so Travis can do its thing :)

change requirements spec to depend on the new Theano release (0.7)

---

lasagne/layers/pool.py
lasagne/tests/layers/test_pool.py

Work in progress on https://github.com/benanne/Lasagne/issues/186.
I think it's functional but I need to figure out some tests for the `ignore_border = False` mode, and update the documentation.

Add support for striding and padding to pooling layers

---

lasagne/layers/noise.py

add docs to DropoutLayer and GaussianNoiseLayer
This is a cleaned up version of PR https://github.com/Lasagne/Lasagne/pull/212

add doc to DropoutLayer and GaussianNoiseLayer

---

lasagne/updates.py

Add docs to 
1.  Adadelta
2. Adagrad
3. RMSprop
Should i include usage examples?

updates.py docs

---

lasagne/init.py
lasagne/tests/test_init.py

Add's docstrings to initializers. 
TODO: Can someone check the Glorot and He descriptions?

Updates init

---

docs/modules/layers.rst
lasagne/layers/pool.py

Cleaned up the docs for the pooling layers a bit further (@ebenolson already did a bunch of work on them before). This is as preparation for the corrmm/cuda_convnet/dnn docs, which I will probably do next.

Pooling layer docs

---

lasagne/utils.py

Cfr. #203. 
I found it to be a bit tricky so it probably needs some work. I only changed the docs for compute_norms to the numpydoc format.

Utils docs

---

docs/modules/layers.rst
lasagne/layers/dnn.py
lasagne/layers/pool.py

This will mostly be copy pasting I guess, but we should probably have dedicated docstrings for all of them anyway because they usually implement some extra features (and sometimes mis a few others).

documentation for the cuDNN-based convolution/pooling layer implementations

---

docs/index.rst
docs/user/custom_layers.rst
docs/user/development.rst
docs/user/installation.rst
docs/user/layers.rst
docs/user/tutorial.rst

I went through the user guide and tried to flesh it out / clean it up a bit where I thought it was necessary. Obviously there is still a bunch more work to do on this once the API has stabilized and we've cleaned up the examples (see #215). Feedback is welcome as always.

Fleshing out / cleaning up the user guide

---

lasagne/layers/base.py
lasagne/layers/helper.py
lasagne/layers/input.py

Documentation: Sphinx format to numpydoc format (rebased)

---

lasagne/layers/__init__.py
lasagne/layers/embedding.py
lasagne/tests/layers/test_embedding.py

Moved from https://github.com/craffel/nntools/pull/28

embedding layer + test

---

lasagne/layers/shape.py
lasagne/tests/layers/test_shape.py

Slicing layer. Thanks to @f0k for a lot of help!
The test might need a little refactoring but i'm not that familiar with pytest

add SliceLayer + test

---

docs/modules/layers.rst
docs/modules/updates.rst
lasagne/layers/conv.py
lasagne/layers/corrmm.py
lasagne/layers/cuda_convnet.py
lasagne/layers/dense.py
lasagne/layers/dnn.py
lasagne/layers/pool.py

This PR makes all function and class signatures look nice (part of #203). I also made `NonlinearityLayer` and `adam` show up in the docs.

fix signatures and a few other things in the docs

---

lasagne/tests/test_updates.py
lasagne/updates.py

Update rule that scales based on the combined norm.
Moved from https://github.com/craffel/nntools/pull/29

step_scaling update rule + test

---

docs/modules/updates.rst
lasagne/updates.py

add total_norm_constraint to updates.rst  and adds a few missing dots.

add total_norm_constraint to updates.rst

---

lasagne/layers/shape.py

add missing `**kwargs` to slicelayer

add kwargs to slice get_output_for

---

docs/modules/objectives.rst
examples/mnist.py
lasagne/objectives.py
lasagne/tests/test_objectives.py

This reworks the `lasagne.objectives` module as per our discussion in #173.
Todo list:
* ~~update occurrences of Objective in the documentation~~ (wasn't mentioned anywhere else)

Rework lasagne.objectives (remove Objective and MaskedObjective)

---

docs/modules/layers.rst
docs/modules/regularization.rst
lasagne/layers/cuda_convnet.py
lasagne/layers/merge.py
lasagne/layers/noise.py
lasagne/layers/shape.py

- adds some missing layers
- removes see also when alias is printed in the docs
- fix bug in dropout ref

fix alias in docs

---

docs/modules/layers.rst
lasagne/layers/merge.py
lasagne/tests/layers/test_merge.py

Add ElemwiseMergeLayer and ElemwiseSumLayer
Im not sure that i added ElemwiseSumLayer correctly to layers.rst

add ElemwiseMergeLayer

---

lasagne/layers/dnn.py

fix Pool2DDNNLayer stride

---

lasagne/utils.py

remove superfluous newline, fixed link to categorical_crossentropy function

fix one_hot doc string note

---

examples/mnist.py

The changes in https://github.com/Lasagne/Lasagne/pull/328 introduced some PEP-8 issues, this commit fixes them.

Fix PEP-8 issues in mnist example

---

lasagne/updates.py

moved two calculations outside the for-zip loop

optimise adam solver

---

docs/user/installation.rst

Correct typo in cuDNN instructions

---

docs/index.rst
docs/modules/random.rst
lasagne/__init__.py
lasagne/init.py
lasagne/layers/noise.py
lasagne/random.py
lasagne/tests/layers/test_noise.py
lasagne/tests/test_init.py

This is intended to address #6.

added support for setting a RandomState other than np.random

---

docs/modules/layers/helper.rst
docs/modules/objectives.rst

Overlooked that in #359, sorry!

Remove deprecated functions and classes from documentation

---

lasagne/layers/recurrent.py
lasagne/tests/layers/test_recurrent.py

Resolves #358.  See the test for a usage example.

Allow more than 1 feature dimension in CustomRecurrentLayer

---

lasagne/updates.py

Correct beta parameter names in adam() docstring

---

lasagne/updates.py

Very small fix of wrong argument name in total_norm_constraint docs.

Small total_norm_constraint doc fix

---

.gitignore
lasagne/nonlinearities.py
lasagne/objectives.py
lasagne/tests/test_objectives.py

So I wanted to add accuracy objective (so that it can be made more general of calculating validation and test statistics such as just passing a handle) as well as hinge loss objectives (I've seen them used often in the NLP papers). Additionally, changed the rectifier to use the theano implementation, because as of the current state they are the same.

More objectives

---

lasagne/objectives.py
lasagne/tests/test_objectives.py

Corrects the spelling of multiclass_hinge_loss (was mutliclass_hinge_loss)

spelling correction

---

lasagne/layers/recurrent.py

Fixes #443.
Fixes float64 error when recurrent layer step functions were using empty placeholder lists. I rewrote all the recurrent layers to use *args.

Avoid empty placeholder tuples in recurrent layers

---

lasagne/layers/recurrent.py

Resolves #452.   Someone (@skaae @f0k @Botev) should double-check my logic.

Clarify CustomRecurrentLayer input_to_hidden docs

---

lasagne/layers/recurrent.py
lasagne/tests/layers/test_recurrent.py

Pass kwargs to CustomRecurrentLayer child layers

---

docs/modules/layers.rst
docs/modules/layers/special.rst
lasagne/layers/special.py
lasagne/tests/layers/test_special.py

So I need to add tests. Plus additionally I'm not sure if I'm not missing with the shape of the parameter, if someone can give me a feedback if there are any hidden corners when it won't broadcast correctly.

ParametricRectifyLayer

---

lasagne/layers/recurrent.py

Change learn_init to default to False in GRULayer

---

lasagne/objectives.py
lasagne/tests/test_objectives.py

This adds a `top_k` parameter to `lasagne.objectives.categorical_accuracy()` to allow computing the top-k accuracy.
If anybody knows a better way of expressing the top-k accuracy in a formula, please comment! If you think omitting the formula would be better than the one I have, also let me know.
Closes #504.

Top-k accuracy

---

lasagne/init.py

Fix relu weight init doc

---

docs/modules/layers.rst
docs/modules/layers/special.rst
lasagne/layers/special.py
lasagne/tests/layers/test_special.py

Add RReLu layer

---

lasagne/init.py

Add missing closing brackets in some lasagne.init docstrings

---

docs/modules/updates.rst
lasagne/updates.py

Adamax was not here: http://lasagne.readthedocs.org/en/latest/modules/updates.html

Add Adamax to docs

---

lasagne/layers/recurrent.py

adds missing elementwise multiplication in lstm docs.

missing odot in lstm docs

---

lasagne/layers/dnn.py
lasagne/layers/pool.py
lasagne/tests/layers/test_pool.py

Fixes #568. First time looking at the codebase, feedback welcome.

Raise error if pooling layers get unexpected input dimension

---

docs/modules/layers.rst
lasagne/layers/dnn.py
lasagne/tests/layers/test_pool.py

Hi
This adds the cuDnn implementation of the Pool3DDNNLayer. Required by https://github.com/Lasagne/Recipes/pull/41.
Cheers,
Michael

Added Pool3DDNNLayer and MaxPool3DDNNLayer

---

docs/modules/layers/special.rst
lasagne/layers/special.py
lasagne/tests/layers/test_special.py

This code implements the thin plate spline spatial transformation layer as described in the Jaderberg NIPS 2015 paper. 
Closes #579

Implemented thin plate spline transformation layer #579

---

lasagne/layers/special.py
lasagne/tests/layers/test_special.py

Moved the computation of the distances between the grid and the source points to the initialization of the layer. This prevents this computation from having to be done on every pass. I detailed this concern in #601. 
The one downside of this is that it requires the grid and thus, the image size, to be specified at layer construction time. 
Closes #601.

Increased speed of thin plate spline transformer layer dramatically

---

lasagne/objectives.py

Change
```
Returns
-------
Theano tensor
An expression for the item-wise squared difference.
```
To
```
Returns
-------
Theano tensor
An expression for the element-wise squared difference.
```

update squared_error docstring

---

lasagne/layers/shape.py
lasagne/tests/layers/test_shape.py

Issue #625 Make FlattenLayer support `None` in input shape

---

lasagne/layers/special.py

Fixes #639. Thanks for reporting!

Fix example in InverseLayer docstring

---

docs/user/installation.rst

This adds a link to the new platform-specific installation guides.

Add link to "From Zero to Lasagne" guides

---

lasagne/layers/conv.py
lasagne/tests/layers/test_conv.py

Addresses the third TODO item in issue #524. Untested work in progress, just to mark that I've started it.

Add TransposedConv2DLayer

---

docs/modules/nonlinearities.rst
lasagne/layers/helper.py
lasagne/layers/special.py
lasagne/updates.py

Since @kli-nlpr is doing a docstring review (thanks!), I'm committing some things I found myself last week. Merging can wait a bit, maybe I'll notice more.

Some docstring fixes

---

lasagne/layers/conv.py

Fix documentation of dilation factor in DilatedConv2DLayer

---

lasagne/nonlinearities.py

Before submitting your pull request, please check these hints!
- If you are not familiar with the github workflow, have a look:
https://guides.github.com/introduction/flow/
In particular, note that in order to update your pull request to include any
changes we asked for, you just need to push to your branch again.
- If your pull request addresses a particular issue from our issue tracker,
reference it in your pull request description on github (not the commit
message) using the syntax `Closes #123` or `Fixes #123`.
Pull request check list:
- Install Lasagne in editable mode to be able to run tests locally:
http://lasagne.readthedocs.io/en/latest/user/development.html#development-setup
- Make sure PEP8 is followed:
`python -m pep8 lasagne/`
- Make sure the test suite runs through:
`python …

fixed typo, EUL=>ELU

---

lasagne/layers/recurrent.py

Fix error in comments for LSTMLayer and GRULayer

---

docs/modules/layers.rst
docs/modules/layers/pool.rst
lasagne/layers/pool.py
lasagne/tests/layers/test_pool.py

Upscale 3Dlayer created in lines with Upscale2D layer for using in recently published volumetric nets such as 3D UNets . Hope  it is fine !

Created an UpScale3D Layer

---

lasagne/layers/conv.py
lasagne/tests/layers/test_conv.py

This PR adds a parameter `alpha` to the transposed convolution layer to let the user specify which of the  possible output shapes to return (when stride is not 1).
Closes #711.

Add parameter to transposed conv to control the output shape

---

lasagne/layers/pool.py
lasagne/tests/layers/test_pool.py

This PR adds a parameter mode to the upscaling pool layer and 'bed of nails' mode for all upscaling layers. This modification does not break compatibility as the default mode is 'repeat' as it was before.
Examples of this method used for unpooling:
https://arxiv.org/abs/1411.5928
https://arxiv.org/abs/1506.02753
https://arxiv.org/abs/1602.02644
Example of differences in modes:
With 'repeat' and old behaviour
```
[[1, 2], 
[3, 4]] 
```
becomes 
```
[[1, 1, 2, 2], 
[1, 1, 2, 2],
[3, 3, 4, 4],
[3, 3, 4, 4]]
```
With 'bed_of_nails' it becomes
```
[[1, 0, 2, 0], 
[0, 0, 0, 0],
[3, 0, 4, 0],
[0, 0, 0, 0]]
```

Add mode bed_of_nails to Upscale1DLayer, Upscale2DLayer, Upscale3DLayer

---

docs/modules/layers.rst
docs/modules/layers/local.rst
lasagne/layers/__init__.py
lasagne/layers/local.py
lasagne/tests/layers/test_local.py

This PR follows up on the discussion from [here](https://groups.google.com/forum/#!topic/lasagne-users/G-LF7JCu9PM). I believe there is no issue relating to this though.

Add LocallyConnected2DLayer, including documentation and tests.

---

lasagne/layers/input.py
lasagne/tests/layers/test_input.py

Support InputLayer shape given as list

---

lasagne/objectives.py
lasagne/tests/test_objectives.py

Use T.square in squared_error

---

lasagne/layers/pool.py

Recent versions of Theano give a UserWarning that the `T.signal.pool.pool_2d` keyword arguments will be renamed. This PR tries the new keyword argument names first, then falls back to the old keyword argument names if Theano is too old.
For an example of the warning, see https://groups.google.com/forum/#!topic/lasagne-users/_sWiCtoZ7H8.

support Theano's new pool_2d interface

---

lasagne/layers/recurrent.py
lasagne/tests/layers/test_recurrent.py

This PR addresses issue #777, allowing the input-to-hidden and hidden-to-hidden layer stacks to have arbitrary depth (with unit tests).

`CustomRecurrentLayer` arbitrary depth layer stacks

---

lasagne/tests/test_utils.py

Two test cases added to fix the problem that was introduced in this PR: https://github.com/Lasagne/Lasagne/pull/836 for the coverage.

add missing tests for create param

---

docs/conf.py
lasagne/layers/conv.py
lasagne/tests/layers/test_conv.py

TransposedConv3DLayer

---

lasagne/random.py

Fixes https://github.com/Lasagne/Lasagne/issues/718

Added a warning note in lasagne/random.py
